#! /bin/bash
_start_container() {
    row=$(schedctl list | grep debug)
    schedctl create -f "$HOME"/debug.json
    #schedctl create --name debug --image "harbor.smoa.cc/public/smore_core:v2.5.0.cu11" --gpu 1 --cmd "sleep 2h" --debug
    start=$(date +%s)
    while [[ $row != *"Running"* ]];do
        row=$(schedctl list | grep debug | awk -F'|' '{print $4}')
        sleep 1
        waited=$(($(date +%s)-start))
        echo -ne "\rwaited $waited seconds"
    done
    echo
}

if [[ $(hostname) == 'debug' ]];then
    echo 'Already in debug container'
    exit 0
fi
row=$(schedctl list | grep debug)
env=$(which python|awk -F'/' '{print $(NF-2)}')
if [[ $env == 'miniconda3' ]];then
    env='base'
fi
curr=$(pwd)
if [[ -n $row && $row != *"Running"* ]];then
    echo 'Debug container exists but not running, terminate first...'
    schedctl delete debug
    while [ "$(schedctl list | rg debug | wc -l)" -gt 0 ];do
        sleep 1
    done
    _start_container "$row"
fi
if [ -z "$row" ];then
    echo 'No debug container found, creating one...'
    _start_container "$row"
fi

port=$(sch describe debug | awk '/Ports/ {getline; print $NF}')
echo "Exposed addr: http://scheduler.smoa.cc:${port}"

if [[ $env == 'base' ]];then
    echo -e "Please exec manually: \ncd $curr"
else
    echo -e "Please exec manually: \nconda activate $env && cd $curr"
fi
schedctl exec debug bash
