#! /bin/bash

if [[ $# -ne 2 || ! -d $1 ]]; then
    echo 'Usage: fork_new_exp <PREV_NAME> <CURR_NAME>'
    exit -1
fi

prev=$1
curr=$2
if [[ ! -e ${curr} ]]; then
    mkdir ${curr};
elif [[ -f ${curr} ]]; then
    echo "Expect ${curr} a directory, but got a file."
fi
cp ${prev}/exp.yaml ${curr}/exp.yaml
cp ${prev}/scheduler.json ${curr}/scheduler.json
if [[ -e ${prev}/.git ]]; then
    cp -r ${prev}/.git ${curr}
fi
if [[ -e ${prev}/customized ]]; then
    cp -r ${prev}/customized ${curr}
fi
